### ISSUE TITLE
Stack fails to build the test suite when type-map is added as an extra dep

### ISSUE THREAD

**Issue by o1lo01ol1o** [Lysxia/type-map#1]
Hi,

This could be my error, but when I add type-map to a stack project (ghc 8.2.2), stack fails to build the project with:

```
Configuring type-map-0.1.0.0...
    Preprocessing library for type-map-0.1.0.0..
    Building library for type-map-0.1.0.0..
    [ 1 of 13] Compiling Data.TypeMap.Check ( src/Data/TypeMap/Check.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Data/TypeMap/Check.o )
    
    /private/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/stack43304/type-map-0.1.0.0/src/Data/TypeMap/Check.hs:7:1: error:
        Could not find module ‘Data.Typeable.Internal’
        it is a hidden module in the package ‘base-4.10.1.0’
        Use -v to see a list of the files searched for.
      |
    7 | import Data.Typeable.Internal
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Would you know how one could get around this?

Thanks.

**Comment by Lysxia** [comment]
Thank you for reporting this! It appears that between `base-4.9` and `4.10`,   `Data.Typeable.Internal` has moved to `Data.Typeable`. Let me fix that!

**Comment by Lysxia** [comment]
`Data.Typeable.Internal` has been hidden in `base-4.10`. I'll get it to work, and in the meantime `type-map` will only work up to `base-4.9`.

**Comment by Lysxia** [comment]
Fixed by https://github.com/Lysxia/type-map/commit/091f81a2b59e89bc45402d518991eb3eb33246dd, now in 0.1.1.0!

**Comment by o1lo01ol1o** [comment]
👍
